modLoader="javafml" #mandatory
loaderVersion="[44,)"
license="LGPLv3"
issueTrackerURL="https://github.com/CorgiTaco/Block-Swap/issues" #optional
[[mods]]
modId="blockswap"
version="${file.jarVersion}"
displayName="Block Swap"
displayURL="https://github.com/CorgiTaco/Block-Swap/"
logoFile="assets/blockswap/blockswap.png"
credits="J.T. McQuigg (JT122406)"
authors="Corgi Taco"
description='''
Simply replaces one block with another.
'''
[[dependencies.blockswap]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44.1,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.blockswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockswap]]
modId = "corgilib"
mandatory = true
versionRange = "[2.0.0.0,)"
ordering = "BEFORE"
side = "BOTH"
