modLoader = "javafml"
loaderVersion = "[33,)"
license = "MIT"
issueTrackerURL = "https://github.com/CorgiTaco/Block-Replacer/issues"
[[mods]]
modId = "blockreplacer"
version = "1.0.0"
displayName = "Block Replacer"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/block-replacer"
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
Simply replaces one block with another
'''
[[dependencies.blockreplacer]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
