modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/Block-Swap/issues"
[[mods]]
modId = "blockswap"
version = "1.1.1"
displayName = "Block Swap"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/Block-Swap"
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
Simply replaces one block with another.
'''
[[dependencies.blockswap]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
