blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://github.com/CorgiTaco/Block-Swap/wiki/Issues-FAQ
    about: Answers to frequently asked questions, may contain an answer to a crash you're having ;)
  - name: Corgi Taco's Discord
    url: https://discord.gg/eWPBm4QFFz
    about: Join our discord to chat with us, ask questions, or make suggestions in regards to Block Swap!
  - name: Wiki
    url: https://github.com/CorgiTaco/Block-Swap/wiki
    about: Information on configuring Block Swap and more!
  - name: Donate
    url: https://www.patreon.com/CorgiTaco
    about: Donate!
